[nfs]
172.31.33.40 ansible_ssh_user='ec2-user'

[webservers]
172.31.85.10 ansible_ssh_user='ec2-user'
172.31.95.48 ansible_ssh_user='ec2-user'

[db]
172.31.84.92 ansible_ssh_user='ec2-user' 

[lb]
172.31.89.34 ansible_ssh_user='ubuntu'
